#%RAML 1.0
title: family_todo
version: v1
baseUri: http://api.samplehost.com

/login:
  post:
    description: Sends user's username and password for authentication
    body:
      application/json:
        example: |
          {
            "username": "JohnDoe01",
            "password": "12345abc"
          }
    responses:
      200:
        description: Login was successful
        body:
          application/xml:
            example: |
              {
                "sessionId": "QWEQWEASD1234DFDFG"
              }
      404:
        description: Username or password is wrong, no such user.
/logout:
  post:
    description: Sends user's session id in order to log him/her out
    body:
      application/json:
        example: |
          {
            "sessionId": "SADFGFDVXCCXV1234GERT%"
          }
    responses:
      200:
        description: Log out was successful.
      404:
        description: The given session id did not exists.
/register:
  post:
    description: Sends registration information in order to register to the website
    body:
      application/xml:
        example: |
          {
            "username": "JohnDoe01",
            "password": "12345abc",
            "name": "John Doe",
            "phoneNumber": 012345,
            "home": "Somewhere",
            "workplace": "Somewhere else
            "birth": 1970.05.22
          }
    responses:
      200:
        description: Registration was successful
      409:
        description: Username already taken
      412:
        description: validation of given data was erronous
        body:
          application/json:
            example: |
              {
                "erronousField":"username"
              }
/users:
  get:
    description: |
                  gets all user's basic info in case of that the user that is requesting
                  is the global administrator
    headers:
      Authorization:
        description: Payload for HTTP basic authentication
        required: true
        example:  Basic QWER!+%%/=
    responses:
      200:
        body:
          application/xml:
            example: |
              {
                "users":
                  [
                    {
                      "id": 1,
                      "username": "JohnDoe01",
                      "name": "John Doe"
                    },
                    {
                      "id": 2,
                      "username": "MaryPoppins",
                      "name": "Mary Poppins"
                    }
                  ]
              }
  /{userId}:
    get:
      description: |
                    gets the specified user's all information in case of that the user
                    that is requesting
                    is the global administrator or they are part of the same family or
                    the userId is the same, as the requester's userId
      headers:
        Authorization:
          description: Payload for HTTP basic authentication
          required: true
          example:  Basic QWER!+%%/=
      responses:
        200:
          body:
            application/xml:
              example: |
                {
                "id": 1,
                "username": "JohnDoe01",
                "name": "John Doe",
                "phoneNumber": 012345,
                "home": "Somewhere",
                "workplace": "Somewhere else",
                "role": "father",
                "birth": 1970.05.22,
                "families": [1,2,4]
                }
        404:
          description: No such user or no permission
    patch:
      description: |
                    Modifies the given user's information if and only if, the specified
                    userId is the same, with the one's who is requesting or he/she is
                    the global administrator.
      headers:
        Authorization:
          description: Payload for HTTP basic authentication
          required: true
          example:  Basic QWER!+%%/=
      body:
        application/json:
          description: The modified information to be persisted in database.
          example: |
            {
              "id": 1,
              "username": "JohnDoe01",
              "password": "12345abc",
              "name": "John Doe",
              "phoneNumber": 012345,
              "home": "Somewhere",
              "workplace": "Somewhere else",
              "role": "father",
              "birth": 1970.05.22
            }
      responses:
        200:
          description: Modification was successful
        404:
          description: No such user or no permission
    delete:
      description: |
                    Deletes the given user if and only if, the specified
                    userId is the same, with the one's who is requesting
                    or he/she is the global administrator.
      headers:
        Authorization:
          description: Payload for HTTP basic authentication
          required: true
          example:  Basic QWER!+%%/=
      responses:
        200:
          description: Deletion was successful.
        404:
          description: No such user or no permission.
    /joinFamily:
      post:
            description: |
                          join to the given family with the specified familyId
                          if and only if the given userId is the same, as the one's
                          who has the dispatched sessionId.
            headers:
              Authorization:
                description: Payload for HTTP basic authentication
                required: true
                example:  Basic QWER!+%%/=
            body:
                application/json:
                  example: |
                    {
                      "familyId": "WDWQER"+!%%"
                    }
/families:
      get:
        description: |
                      Get all families for the specified user
                      that he/she is member of.If he or she is the global
                      administrator then it returns all the families.

        headers:
          Authorization:
            description: Payload for HTTP basic authentication
            required: true
            example:  Basic QWER!+%%/=
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "families":[12,35,43,1]
                  }
          401:
            description: Unauthorized
      post:
        description: Creates a new family.
        headers:
          Authorization:
            description: Payload for HTTP basic authentication
            required: true
            example:  Basic QWER!+%%/=
        body:
          application/json:
            example: |
              {
                "familyName": "Doe's family",
                "adminId": 3
              }
      /{familyId}:
        get:
          description: |
                        Get all information from the specified family if and only if
                        the requester is part of the family or he/she is the
                        global administrator.
          headers:
            Authorization:
              description: Payload for HTTP basic authentication
              required: true
              example:  Basic QWER!+%%/=
          responses:
            200:
              body:
                application/json:
                  example: |
                    {
                      "id": 3,
                      "name": "Doe's family",
                      "adminId": 1
                    }
            401:
              description: Unauthorized
        patch:
          description: |
                        Modify the family that he/she owns as an administrator or as the
                        global administrator.
          headers:
            Authorization:
              description: Payload for HTTP basic authentication
              required: true
              example:  Basic QWER!+%%/=
          body:
            application/json:
              example:
                {
                  "familyName": "OtherDoe's family"
                }
          responses:
            200:
              description: Modification was successful
            404:
              description: no such family or no permission
        delete:
          description: |
                        Deletes the family that he/she owns as an administrator or as the
                        global administrator.
          headers:
            Authorization:
              description: Payload for HTTP basic authentication
              required: true
              example:  Basic QWER!+%%/=
          responses:
            200:
              description: Deletion was successful
            404:
              description: no such family or no permission
